version: '3.8'


services:
  sav-node:
    build:
      context: ./
      dockerfile: Dockerfile
    image: sav-node
    container_name: sav-node
    volumes:
      - ./:/home/
    environment:
      - PORT=8400
      - ENV=LOCAL
      - URL_FRONT=localhost:4200
      - PROTOCAL_FRONT=http
      - VERSION=local
      - DATE_DEPLOY=Sun 18 Apr 2021 07:29:46 AM CEST
      - EMAIL_HOST=ssl0.ovh.net
      - EMAIL_PORT=465
      - EMAIL_USER=dev-team@tic-nova.com
      - EMAIL_PASS=dev-team0
      - PRIVATE_KEY=YjUzNjIwNzNTjkMyOGM7YgFkGZ5NMDZGMxZWjA2Y2zkxMk2ZWZjYjY2NTIyYzA01OTg05U2ZiNEYZTAzFmNhZj
      - MONGO_URI=mongodb+srv://ademsansa7:ademaziz_database@sav-database.iqyiy.mongodb.net/?retryWrites=true&w=majority
    ports:
      - 8500:8400
    depends_on:
      - mongo-sav-node
  mongo-sav-node:
    image: mongo:8.0
    container_name: mongo-sav-node
    volumes:
      - mongo-volume-sav:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - 43080:27017
volumes:
  mongo-volume-sav:
    
